const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
const SET_CURRENT_ORDER = "SET_CURRENT_ORDER";
const CLOSE_MODAL = "CLOSE_MODAL";

export {
    SET_CURRENT_ITEM,
    CLOSE_MODAL,
    SET_CURRENT_ORDER
  };
