const WS_CONNECTION_START = 'WS_CONNECTION_START';
const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
const WS_GET_ORDERS = 'WS_GET_ORDERS';
const WS_GET_USER_ORDERS = 'WS_GET_USER_ORDERS';

export {
  WS_CONNECTION_CLOSED,
  WS_CONNECTION_ERROR,
  WS_CONNECTION_START,
  WS_CONNECTION_SUCCESS,
  WS_GET_ORDERS,
  WS_GET_USER_ORDERS
}
